package com.yfyk.entity;

import java.util.Date;

public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.createDate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.modifyDate
     *
     * @mbggenerated
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.orders
     *
     * @mbggenerated
     */
    private Integer orders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.treePath
     *
     * @mbggenerated
     */
    private String treepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.parent
     *
     * @mbggenerated
     */
    private Long parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.parent_id
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.fullName
     *
     * @mbggenerated
     */
    private String fullname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.id
     *
     * @return the value of t_area.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.id
     *
     * @param id the value for t_area.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.createDate
     *
     * @return the value of t_area.createDate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.createDate
     *
     * @param createdate the value for t_area.createDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.modifyDate
     *
     * @return the value of t_area.modifyDate
     *
     * @mbggenerated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.modifyDate
     *
     * @param modifydate the value for t_area.modifyDate
     *
     * @mbggenerated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.orders
     *
     * @return the value of t_area.orders
     *
     * @mbggenerated
     */
    public Integer getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.orders
     *
     * @param orders the value for t_area.orders
     *
     * @mbggenerated
     */
    public void setOrders(Integer orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.name
     *
     * @return the value of t_area.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.name
     *
     * @param name the value for t_area.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.treePath
     *
     * @return the value of t_area.treePath
     *
     * @mbggenerated
     */
    public String getTreepath() {
        return treepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.treePath
     *
     * @param treepath the value for t_area.treePath
     *
     * @mbggenerated
     */
    public void setTreepath(String treepath) {
        this.treepath = treepath == null ? null : treepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.parent
     *
     * @return the value of t_area.parent
     *
     * @mbggenerated
     */
    public Long getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.parent
     *
     * @param parent the value for t_area.parent
     *
     * @mbggenerated
     */
    public void setParent(Long parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.parent_id
     *
     * @return the value of t_area.parent_id
     *
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.parent_id
     *
     * @param parentId the value for t_area.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.fullName
     *
     * @return the value of t_area.fullName
     *
     * @mbggenerated
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.fullName
     *
     * @param fullname the value for t_area.fullName
     *
     * @mbggenerated
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }
}