package com.yfyk.entity;

import java.util.Date;

public class Expenses {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expenses.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expenses.createDate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expenses.modifyDate
     *
     * @mbggenerated
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expenses.member_id
     *
     * @mbggenerated
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expenses.amount
     *
     * @mbggenerated
     */
    private Float amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expenses.expensesTo
     *
     * @mbggenerated
     */
    private Integer expensesto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expenses.houseInfo_id
     *
     * @mbggenerated
     */
    private Integer houseinfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expenses.expensesType
     *
     * @mbggenerated
     */
    private String expensestype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expenses.id
     *
     * @return the value of t_expenses.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expenses.id
     *
     * @param id the value for t_expenses.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expenses.createDate
     *
     * @return the value of t_expenses.createDate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expenses.createDate
     *
     * @param createdate the value for t_expenses.createDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expenses.modifyDate
     *
     * @return the value of t_expenses.modifyDate
     *
     * @mbggenerated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expenses.modifyDate
     *
     * @param modifydate the value for t_expenses.modifyDate
     *
     * @mbggenerated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expenses.member_id
     *
     * @return the value of t_expenses.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expenses.member_id
     *
     * @param memberId the value for t_expenses.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expenses.amount
     *
     * @return the value of t_expenses.amount
     *
     * @mbggenerated
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expenses.amount
     *
     * @param amount the value for t_expenses.amount
     *
     * @mbggenerated
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expenses.expensesTo
     *
     * @return the value of t_expenses.expensesTo
     *
     * @mbggenerated
     */
    public Integer getExpensesto() {
        return expensesto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expenses.expensesTo
     *
     * @param expensesto the value for t_expenses.expensesTo
     *
     * @mbggenerated
     */
    public void setExpensesto(Integer expensesto) {
        this.expensesto = expensesto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expenses.houseInfo_id
     *
     * @return the value of t_expenses.houseInfo_id
     *
     * @mbggenerated
     */
    public Integer getHouseinfoId() {
        return houseinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expenses.houseInfo_id
     *
     * @param houseinfoId the value for t_expenses.houseInfo_id
     *
     * @mbggenerated
     */
    public void setHouseinfoId(Integer houseinfoId) {
        this.houseinfoId = houseinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expenses.expensesType
     *
     * @return the value of t_expenses.expensesType
     *
     * @mbggenerated
     */
    public String getExpensestype() {
        return expensestype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expenses.expensesType
     *
     * @param expensestype the value for t_expenses.expensesType
     *
     * @mbggenerated
     */
    public void setExpensestype(String expensestype) {
        this.expensestype = expensestype == null ? null : expensestype.trim();
    }
}