package com.yfyk.entity;

import java.util.Date;

public class HouseInfoCrawl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.oid
     *
     * @mbggenerated
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.createDate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.modifyDate
     *
     * @mbggenerated
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.community
     *
     * @mbggenerated
     */
    private String community;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.areaSize
     *
     * @mbggenerated
     */
    private Float areasize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.ban
     *
     * @mbggenerated
     */
    private String ban;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.floor
     *
     * @mbggenerated
     */
    private String floor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.infoPrice
     *
     * @mbggenerated
     */
    private Float infoprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.readTime
     *
     * @mbggenerated
     */
    private Integer readtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.roomNumber
     *
     * @mbggenerated
     */
    private String roomnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.salePrice
     *
     * @mbggenerated
     */
    private Float saleprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.saleWay
     *
     * @mbggenerated
     */
    private String saleway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.area_id
     *
     * @mbggenerated
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.member_id
     *
     * @mbggenerated
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.available
     *
     * @mbggenerated
     */
    private Boolean available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.houseShape
     *
     * @mbggenerated
     */
    private String houseshape;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.priority
     *
     * @mbggenerated
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.checkDate
     *
     * @mbggenerated
     */
    private Date checkdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.checkContent
     *
     * @mbggenerated
     */
    private String checkcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.operate_id
     *
     * @mbggenerated
     */
    private Integer operateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.isChannel
     *
     * @mbggenerated
     */
    private Integer ischannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.memberName
     *
     * @mbggenerated
     */
    private String membername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_crawl.areaName
     *
     * @mbggenerated
     */
    private String areaname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.id
     *
     * @return the value of t_house_info_crawl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.id
     *
     * @param id the value for t_house_info_crawl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.oid
     *
     * @return the value of t_house_info_crawl.oid
     *
     * @mbggenerated
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.oid
     *
     * @param oid the value for t_house_info_crawl.oid
     *
     * @mbggenerated
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.createDate
     *
     * @return the value of t_house_info_crawl.createDate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.createDate
     *
     * @param createdate the value for t_house_info_crawl.createDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.modifyDate
     *
     * @return the value of t_house_info_crawl.modifyDate
     *
     * @mbggenerated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.modifyDate
     *
     * @param modifydate the value for t_house_info_crawl.modifyDate
     *
     * @mbggenerated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.name
     *
     * @return the value of t_house_info_crawl.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.name
     *
     * @param name the value for t_house_info_crawl.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.mobile
     *
     * @return the value of t_house_info_crawl.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.mobile
     *
     * @param mobile the value for t_house_info_crawl.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.phone
     *
     * @return the value of t_house_info_crawl.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.phone
     *
     * @param phone the value for t_house_info_crawl.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.community
     *
     * @return the value of t_house_info_crawl.community
     *
     * @mbggenerated
     */
    public String getCommunity() {
        return community;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.community
     *
     * @param community the value for t_house_info_crawl.community
     *
     * @mbggenerated
     */
    public void setCommunity(String community) {
        this.community = community == null ? null : community.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.areaSize
     *
     * @return the value of t_house_info_crawl.areaSize
     *
     * @mbggenerated
     */
    public Float getAreasize() {
        return areasize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.areaSize
     *
     * @param areasize the value for t_house_info_crawl.areaSize
     *
     * @mbggenerated
     */
    public void setAreasize(Float areasize) {
        this.areasize = areasize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.ban
     *
     * @return the value of t_house_info_crawl.ban
     *
     * @mbggenerated
     */
    public String getBan() {
        return ban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.ban
     *
     * @param ban the value for t_house_info_crawl.ban
     *
     * @mbggenerated
     */
    public void setBan(String ban) {
        this.ban = ban == null ? null : ban.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.floor
     *
     * @return the value of t_house_info_crawl.floor
     *
     * @mbggenerated
     */
    public String getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.floor
     *
     * @param floor the value for t_house_info_crawl.floor
     *
     * @mbggenerated
     */
    public void setFloor(String floor) {
        this.floor = floor == null ? null : floor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.address
     *
     * @return the value of t_house_info_crawl.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.address
     *
     * @param address the value for t_house_info_crawl.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.description
     *
     * @return the value of t_house_info_crawl.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.description
     *
     * @param description the value for t_house_info_crawl.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.infoPrice
     *
     * @return the value of t_house_info_crawl.infoPrice
     *
     * @mbggenerated
     */
    public Float getInfoprice() {
        return infoprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.infoPrice
     *
     * @param infoprice the value for t_house_info_crawl.infoPrice
     *
     * @mbggenerated
     */
    public void setInfoprice(Float infoprice) {
        this.infoprice = infoprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.readTime
     *
     * @return the value of t_house_info_crawl.readTime
     *
     * @mbggenerated
     */
    public Integer getReadtime() {
        return readtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.readTime
     *
     * @param readtime the value for t_house_info_crawl.readTime
     *
     * @mbggenerated
     */
    public void setReadtime(Integer readtime) {
        this.readtime = readtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.roomNumber
     *
     * @return the value of t_house_info_crawl.roomNumber
     *
     * @mbggenerated
     */
    public String getRoomnumber() {
        return roomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.roomNumber
     *
     * @param roomnumber the value for t_house_info_crawl.roomNumber
     *
     * @mbggenerated
     */
    public void setRoomnumber(String roomnumber) {
        this.roomnumber = roomnumber == null ? null : roomnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.salePrice
     *
     * @return the value of t_house_info_crawl.salePrice
     *
     * @mbggenerated
     */
    public Float getSaleprice() {
        return saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.salePrice
     *
     * @param saleprice the value for t_house_info_crawl.salePrice
     *
     * @mbggenerated
     */
    public void setSaleprice(Float saleprice) {
        this.saleprice = saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.saleWay
     *
     * @return the value of t_house_info_crawl.saleWay
     *
     * @mbggenerated
     */
    public String getSaleway() {
        return saleway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.saleWay
     *
     * @param saleway the value for t_house_info_crawl.saleWay
     *
     * @mbggenerated
     */
    public void setSaleway(String saleway) {
        this.saleway = saleway == null ? null : saleway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.status
     *
     * @return the value of t_house_info_crawl.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.status
     *
     * @param status the value for t_house_info_crawl.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.area_id
     *
     * @return the value of t_house_info_crawl.area_id
     *
     * @mbggenerated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.area_id
     *
     * @param areaId the value for t_house_info_crawl.area_id
     *
     * @mbggenerated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.member_id
     *
     * @return the value of t_house_info_crawl.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.member_id
     *
     * @param memberId the value for t_house_info_crawl.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.available
     *
     * @return the value of t_house_info_crawl.available
     *
     * @mbggenerated
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.available
     *
     * @param available the value for t_house_info_crawl.available
     *
     * @mbggenerated
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.houseShape
     *
     * @return the value of t_house_info_crawl.houseShape
     *
     * @mbggenerated
     */
    public String getHouseshape() {
        return houseshape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.houseShape
     *
     * @param houseshape the value for t_house_info_crawl.houseShape
     *
     * @mbggenerated
     */
    public void setHouseshape(String houseshape) {
        this.houseshape = houseshape == null ? null : houseshape.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.priority
     *
     * @return the value of t_house_info_crawl.priority
     *
     * @mbggenerated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.priority
     *
     * @param priority the value for t_house_info_crawl.priority
     *
     * @mbggenerated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.checkDate
     *
     * @return the value of t_house_info_crawl.checkDate
     *
     * @mbggenerated
     */
    public Date getCheckdate() {
        return checkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.checkDate
     *
     * @param checkdate the value for t_house_info_crawl.checkDate
     *
     * @mbggenerated
     */
    public void setCheckdate(Date checkdate) {
        this.checkdate = checkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.checkContent
     *
     * @return the value of t_house_info_crawl.checkContent
     *
     * @mbggenerated
     */
    public String getCheckcontent() {
        return checkcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.checkContent
     *
     * @param checkcontent the value for t_house_info_crawl.checkContent
     *
     * @mbggenerated
     */
    public void setCheckcontent(String checkcontent) {
        this.checkcontent = checkcontent == null ? null : checkcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.operate_id
     *
     * @return the value of t_house_info_crawl.operate_id
     *
     * @mbggenerated
     */
    public Integer getOperateId() {
        return operateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.operate_id
     *
     * @param operateId the value for t_house_info_crawl.operate_id
     *
     * @mbggenerated
     */
    public void setOperateId(Integer operateId) {
        this.operateId = operateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.isChannel
     *
     * @return the value of t_house_info_crawl.isChannel
     *
     * @mbggenerated
     */
    public Integer getIschannel() {
        return ischannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.isChannel
     *
     * @param ischannel the value for t_house_info_crawl.isChannel
     *
     * @mbggenerated
     */
    public void setIschannel(Integer ischannel) {
        this.ischannel = ischannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.memberName
     *
     * @return the value of t_house_info_crawl.memberName
     *
     * @mbggenerated
     */
    public String getMembername() {
        return membername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.memberName
     *
     * @param membername the value for t_house_info_crawl.memberName
     *
     * @mbggenerated
     */
    public void setMembername(String membername) {
        this.membername = membername == null ? null : membername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_crawl.areaName
     *
     * @return the value of t_house_info_crawl.areaName
     *
     * @mbggenerated
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_crawl.areaName
     *
     * @param areaname the value for t_house_info_crawl.areaName
     *
     * @mbggenerated
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }
}