package com.yfyk.entity;

import java.util.Date;

public class HouseInfoProperty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.createDate
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.modifyDate
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.community
     *
     * @mbggenerated
     */
    private String community;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.ban
     *
     * @mbggenerated
     */
    private String ban;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.roomNumber
     *
     * @mbggenerated
     */
    private String roomNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.district
     *
     * @mbggenerated
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.town
     *
     * @mbggenerated
     */
    private String town;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.areaId
     *
     * @mbggenerated
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.communityId
     *
     * @mbggenerated
     */
    private Integer communityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.id
     *
     * @return the value of t_house_info_property.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.id
     *
     * @param id the value for t_house_info_property.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.createDate
     *
     * @return the value of t_house_info_property.createDate
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.createDate
     *
     * @param createDate the value for t_house_info_property.createDate
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.modifyDate
     *
     * @return the value of t_house_info_property.modifyDate
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.modifyDate
     *
     * @param modifyDate the value for t_house_info_property.modifyDate
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.name
     *
     * @return the value of t_house_info_property.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.name
     *
     * @param name the value for t_house_info_property.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.address
     *
     * @return the value of t_house_info_property.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.address
     *
     * @param address the value for t_house_info_property.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.mobile
     *
     * @return the value of t_house_info_property.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.mobile
     *
     * @param mobile the value for t_house_info_property.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.community
     *
     * @return the value of t_house_info_property.community
     *
     * @mbggenerated
     */
    public String getCommunity() {
        return community;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.community
     *
     * @param community the value for t_house_info_property.community
     *
     * @mbggenerated
     */
    public void setCommunity(String community) {
        this.community = community == null ? null : community.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.ban
     *
     * @return the value of t_house_info_property.ban
     *
     * @mbggenerated
     */
    public String getBan() {
        return ban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.ban
     *
     * @param ban the value for t_house_info_property.ban
     *
     * @mbggenerated
     */
    public void setBan(String ban) {
        this.ban = ban == null ? null : ban.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.roomNumber
     *
     * @return the value of t_house_info_property.roomNumber
     *
     * @mbggenerated
     */
    public String getRoomNumber() {
        return roomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.roomNumber
     *
     * @param roomNumber the value for t_house_info_property.roomNumber
     *
     * @mbggenerated
     */
    public void setRoomNumber(String roomNumber) {
        this.roomNumber = roomNumber == null ? null : roomNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.status
     *
     * @return the value of t_house_info_property.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.status
     *
     * @param status the value for t_house_info_property.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.district
     *
     * @return the value of t_house_info_property.district
     *
     * @mbggenerated
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.district
     *
     * @param district the value for t_house_info_property.district
     *
     * @mbggenerated
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.town
     *
     * @return the value of t_house_info_property.town
     *
     * @mbggenerated
     */
    public String getTown() {
        return town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.town
     *
     * @param town the value for t_house_info_property.town
     *
     * @mbggenerated
     */
    public void setTown(String town) {
        this.town = town == null ? null : town.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.areaId
     *
     * @return the value of t_house_info_property.areaId
     *
     * @mbggenerated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.areaId
     *
     * @param areaId the value for t_house_info_property.areaId
     *
     * @mbggenerated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.communityId
     *
     * @return the value of t_house_info_property.communityId
     *
     * @mbggenerated
     */
    public Integer getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.communityId
     *
     * @param communityId the value for t_house_info_property.communityId
     *
     * @mbggenerated
     */
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }
}