package com.yfyk.entity;

import java.util.Date;

public class HouseInfoProperty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.oid
     *
     * @mbggenerated
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.createDate
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.modifyDate
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.community
     *
     * @mbggenerated
     */
    private String community;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.areaSize
     *
     * @mbggenerated
     */
    private Float areaSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.ban
     *
     * @mbggenerated
     */
    private String ban;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.floor
     *
     * @mbggenerated
     */
    private String floor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.infoPrice
     *
     * @mbggenerated
     */
    private Float infoPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.readTime
     *
     * @mbggenerated
     */
    private Integer readTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.roomNumber
     *
     * @mbggenerated
     */
    private String roomNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.salePrice
     *
     * @mbggenerated
     */
    private Float salePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.saleWay
     *
     * @mbggenerated
     */
    private String saleWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.area_id
     *
     * @mbggenerated
     */
    private Integer area_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.member_id
     *
     * @mbggenerated
     */
    private Integer member_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.available
     *
     * @mbggenerated
     */
    private Boolean available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.houseShape
     *
     * @mbggenerated
     */
    private String houseShape;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.priority
     *
     * @mbggenerated
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.checkDate
     *
     * @mbggenerated
     */
    private Date checkDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.checkContent
     *
     * @mbggenerated
     */
    private String checkContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.operate_id
     *
     * @mbggenerated
     */
    private Integer operate_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.isChannel
     *
     * @mbggenerated
     */
    private Integer isChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.memberName
     *
     * @mbggenerated
     */
    private String memberName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house_info_property.areaName
     *
     * @mbggenerated
     */
    private String areaName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.id
     *
     * @return the value of t_house_info_property.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.id
     *
     * @param id the value for t_house_info_property.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.oid
     *
     * @return the value of t_house_info_property.oid
     *
     * @mbggenerated
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.oid
     *
     * @param oid the value for t_house_info_property.oid
     *
     * @mbggenerated
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.createDate
     *
     * @return the value of t_house_info_property.createDate
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.createDate
     *
     * @param createDate the value for t_house_info_property.createDate
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.modifyDate
     *
     * @return the value of t_house_info_property.modifyDate
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.modifyDate
     *
     * @param modifyDate the value for t_house_info_property.modifyDate
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.name
     *
     * @return the value of t_house_info_property.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.name
     *
     * @param name the value for t_house_info_property.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.mobile
     *
     * @return the value of t_house_info_property.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.mobile
     *
     * @param mobile the value for t_house_info_property.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.phone
     *
     * @return the value of t_house_info_property.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.phone
     *
     * @param phone the value for t_house_info_property.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.community
     *
     * @return the value of t_house_info_property.community
     *
     * @mbggenerated
     */
    public String getCommunity() {
        return community;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.community
     *
     * @param community the value for t_house_info_property.community
     *
     * @mbggenerated
     */
    public void setCommunity(String community) {
        this.community = community == null ? null : community.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.areaSize
     *
     * @return the value of t_house_info_property.areaSize
     *
     * @mbggenerated
     */
    public Float getAreaSize() {
        return areaSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.areaSize
     *
     * @param areaSize the value for t_house_info_property.areaSize
     *
     * @mbggenerated
     */
    public void setAreaSize(Float areaSize) {
        this.areaSize = areaSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.ban
     *
     * @return the value of t_house_info_property.ban
     *
     * @mbggenerated
     */
    public String getBan() {
        return ban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.ban
     *
     * @param ban the value for t_house_info_property.ban
     *
     * @mbggenerated
     */
    public void setBan(String ban) {
        this.ban = ban == null ? null : ban.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.floor
     *
     * @return the value of t_house_info_property.floor
     *
     * @mbggenerated
     */
    public String getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.floor
     *
     * @param floor the value for t_house_info_property.floor
     *
     * @mbggenerated
     */
    public void setFloor(String floor) {
        this.floor = floor == null ? null : floor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.address
     *
     * @return the value of t_house_info_property.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.address
     *
     * @param address the value for t_house_info_property.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.description
     *
     * @return the value of t_house_info_property.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.description
     *
     * @param description the value for t_house_info_property.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.infoPrice
     *
     * @return the value of t_house_info_property.infoPrice
     *
     * @mbggenerated
     */
    public Float getInfoPrice() {
        return infoPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.infoPrice
     *
     * @param infoPrice the value for t_house_info_property.infoPrice
     *
     * @mbggenerated
     */
    public void setInfoPrice(Float infoPrice) {
        this.infoPrice = infoPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.readTime
     *
     * @return the value of t_house_info_property.readTime
     *
     * @mbggenerated
     */
    public Integer getReadTime() {
        return readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.readTime
     *
     * @param readTime the value for t_house_info_property.readTime
     *
     * @mbggenerated
     */
    public void setReadTime(Integer readTime) {
        this.readTime = readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.roomNumber
     *
     * @return the value of t_house_info_property.roomNumber
     *
     * @mbggenerated
     */
    public String getRoomNumber() {
        return roomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.roomNumber
     *
     * @param roomNumber the value for t_house_info_property.roomNumber
     *
     * @mbggenerated
     */
    public void setRoomNumber(String roomNumber) {
        this.roomNumber = roomNumber == null ? null : roomNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.salePrice
     *
     * @return the value of t_house_info_property.salePrice
     *
     * @mbggenerated
     */
    public Float getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.salePrice
     *
     * @param salePrice the value for t_house_info_property.salePrice
     *
     * @mbggenerated
     */
    public void setSalePrice(Float salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.saleWay
     *
     * @return the value of t_house_info_property.saleWay
     *
     * @mbggenerated
     */
    public String getSaleWay() {
        return saleWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.saleWay
     *
     * @param saleWay the value for t_house_info_property.saleWay
     *
     * @mbggenerated
     */
    public void setSaleWay(String saleWay) {
        this.saleWay = saleWay == null ? null : saleWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.status
     *
     * @return the value of t_house_info_property.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.status
     *
     * @param status the value for t_house_info_property.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.area_id
     *
     * @return the value of t_house_info_property.area_id
     *
     * @mbggenerated
     */
    public Integer getArea_id() {
        return area_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.area_id
     *
     * @param area_id the value for t_house_info_property.area_id
     *
     * @mbggenerated
     */
    public void setArea_id(Integer area_id) {
        this.area_id = area_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.member_id
     *
     * @return the value of t_house_info_property.member_id
     *
     * @mbggenerated
     */
    public Integer getMember_id() {
        return member_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.member_id
     *
     * @param member_id the value for t_house_info_property.member_id
     *
     * @mbggenerated
     */
    public void setMember_id(Integer member_id) {
        this.member_id = member_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.available
     *
     * @return the value of t_house_info_property.available
     *
     * @mbggenerated
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.available
     *
     * @param available the value for t_house_info_property.available
     *
     * @mbggenerated
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.houseShape
     *
     * @return the value of t_house_info_property.houseShape
     *
     * @mbggenerated
     */
    public String getHouseShape() {
        return houseShape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.houseShape
     *
     * @param houseShape the value for t_house_info_property.houseShape
     *
     * @mbggenerated
     */
    public void setHouseShape(String houseShape) {
        this.houseShape = houseShape == null ? null : houseShape.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.priority
     *
     * @return the value of t_house_info_property.priority
     *
     * @mbggenerated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.priority
     *
     * @param priority the value for t_house_info_property.priority
     *
     * @mbggenerated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.checkDate
     *
     * @return the value of t_house_info_property.checkDate
     *
     * @mbggenerated
     */
    public Date getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.checkDate
     *
     * @param checkDate the value for t_house_info_property.checkDate
     *
     * @mbggenerated
     */
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.checkContent
     *
     * @return the value of t_house_info_property.checkContent
     *
     * @mbggenerated
     */
    public String getCheckContent() {
        return checkContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.checkContent
     *
     * @param checkContent the value for t_house_info_property.checkContent
     *
     * @mbggenerated
     */
    public void setCheckContent(String checkContent) {
        this.checkContent = checkContent == null ? null : checkContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.operate_id
     *
     * @return the value of t_house_info_property.operate_id
     *
     * @mbggenerated
     */
    public Integer getOperate_id() {
        return operate_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.operate_id
     *
     * @param operate_id the value for t_house_info_property.operate_id
     *
     * @mbggenerated
     */
    public void setOperate_id(Integer operate_id) {
        this.operate_id = operate_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.isChannel
     *
     * @return the value of t_house_info_property.isChannel
     *
     * @mbggenerated
     */
    public Integer getIsChannel() {
        return isChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.isChannel
     *
     * @param isChannel the value for t_house_info_property.isChannel
     *
     * @mbggenerated
     */
    public void setIsChannel(Integer isChannel) {
        this.isChannel = isChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.memberName
     *
     * @return the value of t_house_info_property.memberName
     *
     * @mbggenerated
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.memberName
     *
     * @param memberName the value for t_house_info_property.memberName
     *
     * @mbggenerated
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house_info_property.areaName
     *
     * @return the value of t_house_info_property.areaName
     *
     * @mbggenerated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house_info_property.areaName
     *
     * @param areaName the value for t_house_info_property.areaName
     *
     * @mbggenerated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }
}