package com.yfyk.entity;

import java.util.Date;

public class Income {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.createDate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.modifyDate
     *
     * @mbggenerated
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.amount
     *
     * @mbggenerated
     */
    private Float amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.member_id
     *
     * @mbggenerated
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.incomeFrom
     *
     * @mbggenerated
     */
    private Integer incomefrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.houseInfo_id
     *
     * @mbggenerated
     */
    private Integer houseinfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_income.incomeType
     *
     * @mbggenerated
     */
    private String incometype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.id
     *
     * @return the value of t_income.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.id
     *
     * @param id the value for t_income.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.createDate
     *
     * @return the value of t_income.createDate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.createDate
     *
     * @param createdate the value for t_income.createDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.modifyDate
     *
     * @return the value of t_income.modifyDate
     *
     * @mbggenerated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.modifyDate
     *
     * @param modifydate the value for t_income.modifyDate
     *
     * @mbggenerated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.amount
     *
     * @return the value of t_income.amount
     *
     * @mbggenerated
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.amount
     *
     * @param amount the value for t_income.amount
     *
     * @mbggenerated
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.member_id
     *
     * @return the value of t_income.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.member_id
     *
     * @param memberId the value for t_income.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.incomeFrom
     *
     * @return the value of t_income.incomeFrom
     *
     * @mbggenerated
     */
    public Integer getIncomefrom() {
        return incomefrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.incomeFrom
     *
     * @param incomefrom the value for t_income.incomeFrom
     *
     * @mbggenerated
     */
    public void setIncomefrom(Integer incomefrom) {
        this.incomefrom = incomefrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.houseInfo_id
     *
     * @return the value of t_income.houseInfo_id
     *
     * @mbggenerated
     */
    public Integer getHouseinfoId() {
        return houseinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.houseInfo_id
     *
     * @param houseinfoId the value for t_income.houseInfo_id
     *
     * @mbggenerated
     */
    public void setHouseinfoId(Integer houseinfoId) {
        this.houseinfoId = houseinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_income.incomeType
     *
     * @return the value of t_income.incomeType
     *
     * @mbggenerated
     */
    public String getIncometype() {
        return incometype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_income.incomeType
     *
     * @param incometype the value for t_income.incomeType
     *
     * @mbggenerated
     */
    public void setIncometype(String incometype) {
        this.incometype = incometype == null ? null : incometype.trim();
    }
}