package com.yfyk.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MemberExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_member
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_member
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_member
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated
     */
    public MemberExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_member
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createDate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("createDate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("createDate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("createDate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("createDate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("createDate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("createDate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("createDate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("createDate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("createDate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("createDate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNull() {
            addCriterion("modifyDate is null");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNotNull() {
            addCriterion("modifyDate is not null");
            return (Criteria) this;
        }

        public Criteria andModifydateEqualTo(Date value) {
            addCriterion("modifyDate =", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotEqualTo(Date value) {
            addCriterion("modifyDate <>", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThan(Date value) {
            addCriterion("modifyDate >", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThanOrEqualTo(Date value) {
            addCriterion("modifyDate >=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThan(Date value) {
            addCriterion("modifyDate <", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThanOrEqualTo(Date value) {
            addCriterion("modifyDate <=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateIn(List<Date> values) {
            addCriterion("modifyDate in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotIn(List<Date> values) {
            addCriterion("modifyDate not in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateBetween(Date value1, Date value2) {
            addCriterion("modifyDate between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotBetween(Date value1, Date value2) {
            addCriterion("modifyDate not between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andBalanceIsNull() {
            addCriterion("balance is null");
            return (Criteria) this;
        }

        public Criteria andBalanceIsNotNull() {
            addCriterion("balance is not null");
            return (Criteria) this;
        }

        public Criteria andBalanceEqualTo(Float value) {
            addCriterion("balance =", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotEqualTo(Float value) {
            addCriterion("balance <>", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceGreaterThan(Float value) {
            addCriterion("balance >", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceGreaterThanOrEqualTo(Float value) {
            addCriterion("balance >=", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceLessThan(Float value) {
            addCriterion("balance <", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceLessThanOrEqualTo(Float value) {
            addCriterion("balance <=", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceIn(List<Float> values) {
            addCriterion("balance in", values, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotIn(List<Float> values) {
            addCriterion("balance not in", values, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceBetween(Float value1, Float value2) {
            addCriterion("balance between", value1, value2, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotBetween(Float value1, Float value2) {
            addCriterion("balance not between", value1, value2, "balance");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andIsenabledIsNull() {
            addCriterion("isEnabled is null");
            return (Criteria) this;
        }

        public Criteria andIsenabledIsNotNull() {
            addCriterion("isEnabled is not null");
            return (Criteria) this;
        }

        public Criteria andIsenabledEqualTo(Boolean value) {
            addCriterion("isEnabled =", value, "isenabled");
            return (Criteria) this;
        }

        public Criteria andIsenabledNotEqualTo(Boolean value) {
            addCriterion("isEnabled <>", value, "isenabled");
            return (Criteria) this;
        }

        public Criteria andIsenabledGreaterThan(Boolean value) {
            addCriterion("isEnabled >", value, "isenabled");
            return (Criteria) this;
        }

        public Criteria andIsenabledGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isEnabled >=", value, "isenabled");
            return (Criteria) this;
        }

        public Criteria andIsenabledLessThan(Boolean value) {
            addCriterion("isEnabled <", value, "isenabled");
            return (Criteria) this;
        }

        public Criteria andIsenabledLessThanOrEqualTo(Boolean value) {
            addCriterion("isEnabled <=", value, "isenabled");
            return (Criteria) this;
        }

        public Criteria andIsenabledIn(List<Boolean> values) {
            addCriterion("isEnabled in", values, "isenabled");
            return (Criteria) this;
        }

        public Criteria andIsenabledNotIn(List<Boolean> values) {
            addCriterion("isEnabled not in", values, "isenabled");
            return (Criteria) this;
        }

        public Criteria andIsenabledBetween(Boolean value1, Boolean value2) {
            addCriterion("isEnabled between", value1, value2, "isenabled");
            return (Criteria) this;
        }

        public Criteria andIsenabledNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isEnabled not between", value1, value2, "isenabled");
            return (Criteria) this;
        }

        public Criteria andIslockedIsNull() {
            addCriterion("isLocked is null");
            return (Criteria) this;
        }

        public Criteria andIslockedIsNotNull() {
            addCriterion("isLocked is not null");
            return (Criteria) this;
        }

        public Criteria andIslockedEqualTo(Boolean value) {
            addCriterion("isLocked =", value, "islocked");
            return (Criteria) this;
        }

        public Criteria andIslockedNotEqualTo(Boolean value) {
            addCriterion("isLocked <>", value, "islocked");
            return (Criteria) this;
        }

        public Criteria andIslockedGreaterThan(Boolean value) {
            addCriterion("isLocked >", value, "islocked");
            return (Criteria) this;
        }

        public Criteria andIslockedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isLocked >=", value, "islocked");
            return (Criteria) this;
        }

        public Criteria andIslockedLessThan(Boolean value) {
            addCriterion("isLocked <", value, "islocked");
            return (Criteria) this;
        }

        public Criteria andIslockedLessThanOrEqualTo(Boolean value) {
            addCriterion("isLocked <=", value, "islocked");
            return (Criteria) this;
        }

        public Criteria andIslockedIn(List<Boolean> values) {
            addCriterion("isLocked in", values, "islocked");
            return (Criteria) this;
        }

        public Criteria andIslockedNotIn(List<Boolean> values) {
            addCriterion("isLocked not in", values, "islocked");
            return (Criteria) this;
        }

        public Criteria andIslockedBetween(Boolean value1, Boolean value2) {
            addCriterion("isLocked between", value1, value2, "islocked");
            return (Criteria) this;
        }

        public Criteria andIslockedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isLocked not between", value1, value2, "islocked");
            return (Criteria) this;
        }

        public Criteria andLockeddateIsNull() {
            addCriterion("lockedDate is null");
            return (Criteria) this;
        }

        public Criteria andLockeddateIsNotNull() {
            addCriterion("lockedDate is not null");
            return (Criteria) this;
        }

        public Criteria andLockeddateEqualTo(Date value) {
            addCriterion("lockedDate =", value, "lockeddate");
            return (Criteria) this;
        }

        public Criteria andLockeddateNotEqualTo(Date value) {
            addCriterion("lockedDate <>", value, "lockeddate");
            return (Criteria) this;
        }

        public Criteria andLockeddateGreaterThan(Date value) {
            addCriterion("lockedDate >", value, "lockeddate");
            return (Criteria) this;
        }

        public Criteria andLockeddateGreaterThanOrEqualTo(Date value) {
            addCriterion("lockedDate >=", value, "lockeddate");
            return (Criteria) this;
        }

        public Criteria andLockeddateLessThan(Date value) {
            addCriterion("lockedDate <", value, "lockeddate");
            return (Criteria) this;
        }

        public Criteria andLockeddateLessThanOrEqualTo(Date value) {
            addCriterion("lockedDate <=", value, "lockeddate");
            return (Criteria) this;
        }

        public Criteria andLockeddateIn(List<Date> values) {
            addCriterion("lockedDate in", values, "lockeddate");
            return (Criteria) this;
        }

        public Criteria andLockeddateNotIn(List<Date> values) {
            addCriterion("lockedDate not in", values, "lockeddate");
            return (Criteria) this;
        }

        public Criteria andLockeddateBetween(Date value1, Date value2) {
            addCriterion("lockedDate between", value1, value2, "lockeddate");
            return (Criteria) this;
        }

        public Criteria andLockeddateNotBetween(Date value1, Date value2) {
            addCriterion("lockedDate not between", value1, value2, "lockeddate");
            return (Criteria) this;
        }

        public Criteria andLogindateIsNull() {
            addCriterion("loginDate is null");
            return (Criteria) this;
        }

        public Criteria andLogindateIsNotNull() {
            addCriterion("loginDate is not null");
            return (Criteria) this;
        }

        public Criteria andLogindateEqualTo(Date value) {
            addCriterion("loginDate =", value, "logindate");
            return (Criteria) this;
        }

        public Criteria andLogindateNotEqualTo(Date value) {
            addCriterion("loginDate <>", value, "logindate");
            return (Criteria) this;
        }

        public Criteria andLogindateGreaterThan(Date value) {
            addCriterion("loginDate >", value, "logindate");
            return (Criteria) this;
        }

        public Criteria andLogindateGreaterThanOrEqualTo(Date value) {
            addCriterion("loginDate >=", value, "logindate");
            return (Criteria) this;
        }

        public Criteria andLogindateLessThan(Date value) {
            addCriterion("loginDate <", value, "logindate");
            return (Criteria) this;
        }

        public Criteria andLogindateLessThanOrEqualTo(Date value) {
            addCriterion("loginDate <=", value, "logindate");
            return (Criteria) this;
        }

        public Criteria andLogindateIn(List<Date> values) {
            addCriterion("loginDate in", values, "logindate");
            return (Criteria) this;
        }

        public Criteria andLogindateNotIn(List<Date> values) {
            addCriterion("loginDate not in", values, "logindate");
            return (Criteria) this;
        }

        public Criteria andLogindateBetween(Date value1, Date value2) {
            addCriterion("loginDate between", value1, value2, "logindate");
            return (Criteria) this;
        }

        public Criteria andLogindateNotBetween(Date value1, Date value2) {
            addCriterion("loginDate not between", value1, value2, "logindate");
            return (Criteria) this;
        }

        public Criteria andLoginfailurecountIsNull() {
            addCriterion("loginFailureCount is null");
            return (Criteria) this;
        }

        public Criteria andLoginfailurecountIsNotNull() {
            addCriterion("loginFailureCount is not null");
            return (Criteria) this;
        }

        public Criteria andLoginfailurecountEqualTo(Integer value) {
            addCriterion("loginFailureCount =", value, "loginfailurecount");
            return (Criteria) this;
        }

        public Criteria andLoginfailurecountNotEqualTo(Integer value) {
            addCriterion("loginFailureCount <>", value, "loginfailurecount");
            return (Criteria) this;
        }

        public Criteria andLoginfailurecountGreaterThan(Integer value) {
            addCriterion("loginFailureCount >", value, "loginfailurecount");
            return (Criteria) this;
        }

        public Criteria andLoginfailurecountGreaterThanOrEqualTo(Integer value) {
            addCriterion("loginFailureCount >=", value, "loginfailurecount");
            return (Criteria) this;
        }

        public Criteria andLoginfailurecountLessThan(Integer value) {
            addCriterion("loginFailureCount <", value, "loginfailurecount");
            return (Criteria) this;
        }

        public Criteria andLoginfailurecountLessThanOrEqualTo(Integer value) {
            addCriterion("loginFailureCount <=", value, "loginfailurecount");
            return (Criteria) this;
        }

        public Criteria andLoginfailurecountIn(List<Integer> values) {
            addCriterion("loginFailureCount in", values, "loginfailurecount");
            return (Criteria) this;
        }

        public Criteria andLoginfailurecountNotIn(List<Integer> values) {
            addCriterion("loginFailureCount not in", values, "loginfailurecount");
            return (Criteria) this;
        }

        public Criteria andLoginfailurecountBetween(Integer value1, Integer value2) {
            addCriterion("loginFailureCount between", value1, value2, "loginfailurecount");
            return (Criteria) this;
        }

        public Criteria andLoginfailurecountNotBetween(Integer value1, Integer value2) {
            addCriterion("loginFailureCount not between", value1, value2, "loginfailurecount");
            return (Criteria) this;
        }

        public Criteria andLoginipIsNull() {
            addCriterion("loginIp is null");
            return (Criteria) this;
        }

        public Criteria andLoginipIsNotNull() {
            addCriterion("loginIp is not null");
            return (Criteria) this;
        }

        public Criteria andLoginipEqualTo(String value) {
            addCriterion("loginIp =", value, "loginip");
            return (Criteria) this;
        }

        public Criteria andLoginipNotEqualTo(String value) {
            addCriterion("loginIp <>", value, "loginip");
            return (Criteria) this;
        }

        public Criteria andLoginipGreaterThan(String value) {
            addCriterion("loginIp >", value, "loginip");
            return (Criteria) this;
        }

        public Criteria andLoginipGreaterThanOrEqualTo(String value) {
            addCriterion("loginIp >=", value, "loginip");
            return (Criteria) this;
        }

        public Criteria andLoginipLessThan(String value) {
            addCriterion("loginIp <", value, "loginip");
            return (Criteria) this;
        }

        public Criteria andLoginipLessThanOrEqualTo(String value) {
            addCriterion("loginIp <=", value, "loginip");
            return (Criteria) this;
        }

        public Criteria andLoginipLike(String value) {
            addCriterion("loginIp like", value, "loginip");
            return (Criteria) this;
        }

        public Criteria andLoginipNotLike(String value) {
            addCriterion("loginIp not like", value, "loginip");
            return (Criteria) this;
        }

        public Criteria andLoginipIn(List<String> values) {
            addCriterion("loginIp in", values, "loginip");
            return (Criteria) this;
        }

        public Criteria andLoginipNotIn(List<String> values) {
            addCriterion("loginIp not in", values, "loginip");
            return (Criteria) this;
        }

        public Criteria andLoginipBetween(String value1, String value2) {
            addCriterion("loginIp between", value1, value2, "loginip");
            return (Criteria) this;
        }

        public Criteria andLoginipNotBetween(String value1, String value2) {
            addCriterion("loginIp not between", value1, value2, "loginip");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andRegisteripIsNull() {
            addCriterion("registerIp is null");
            return (Criteria) this;
        }

        public Criteria andRegisteripIsNotNull() {
            addCriterion("registerIp is not null");
            return (Criteria) this;
        }

        public Criteria andRegisteripEqualTo(String value) {
            addCriterion("registerIp =", value, "registerip");
            return (Criteria) this;
        }

        public Criteria andRegisteripNotEqualTo(String value) {
            addCriterion("registerIp <>", value, "registerip");
            return (Criteria) this;
        }

        public Criteria andRegisteripGreaterThan(String value) {
            addCriterion("registerIp >", value, "registerip");
            return (Criteria) this;
        }

        public Criteria andRegisteripGreaterThanOrEqualTo(String value) {
            addCriterion("registerIp >=", value, "registerip");
            return (Criteria) this;
        }

        public Criteria andRegisteripLessThan(String value) {
            addCriterion("registerIp <", value, "registerip");
            return (Criteria) this;
        }

        public Criteria andRegisteripLessThanOrEqualTo(String value) {
            addCriterion("registerIp <=", value, "registerip");
            return (Criteria) this;
        }

        public Criteria andRegisteripLike(String value) {
            addCriterion("registerIp like", value, "registerip");
            return (Criteria) this;
        }

        public Criteria andRegisteripNotLike(String value) {
            addCriterion("registerIp not like", value, "registerip");
            return (Criteria) this;
        }

        public Criteria andRegisteripIn(List<String> values) {
            addCriterion("registerIp in", values, "registerip");
            return (Criteria) this;
        }

        public Criteria andRegisteripNotIn(List<String> values) {
            addCriterion("registerIp not in", values, "registerip");
            return (Criteria) this;
        }

        public Criteria andRegisteripBetween(String value1, String value2) {
            addCriterion("registerIp between", value1, value2, "registerip");
            return (Criteria) this;
        }

        public Criteria andRegisteripNotBetween(String value1, String value2) {
            addCriterion("registerIp not between", value1, value2, "registerip");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andSafekeyexpireIsNull() {
            addCriterion("safeKeyExpire is null");
            return (Criteria) this;
        }

        public Criteria andSafekeyexpireIsNotNull() {
            addCriterion("safeKeyExpire is not null");
            return (Criteria) this;
        }

        public Criteria andSafekeyexpireEqualTo(Date value) {
            addCriterion("safeKeyExpire =", value, "safekeyexpire");
            return (Criteria) this;
        }

        public Criteria andSafekeyexpireNotEqualTo(Date value) {
            addCriterion("safeKeyExpire <>", value, "safekeyexpire");
            return (Criteria) this;
        }

        public Criteria andSafekeyexpireGreaterThan(Date value) {
            addCriterion("safeKeyExpire >", value, "safekeyexpire");
            return (Criteria) this;
        }

        public Criteria andSafekeyexpireGreaterThanOrEqualTo(Date value) {
            addCriterion("safeKeyExpire >=", value, "safekeyexpire");
            return (Criteria) this;
        }

        public Criteria andSafekeyexpireLessThan(Date value) {
            addCriterion("safeKeyExpire <", value, "safekeyexpire");
            return (Criteria) this;
        }

        public Criteria andSafekeyexpireLessThanOrEqualTo(Date value) {
            addCriterion("safeKeyExpire <=", value, "safekeyexpire");
            return (Criteria) this;
        }

        public Criteria andSafekeyexpireIn(List<Date> values) {
            addCriterion("safeKeyExpire in", values, "safekeyexpire");
            return (Criteria) this;
        }

        public Criteria andSafekeyexpireNotIn(List<Date> values) {
            addCriterion("safeKeyExpire not in", values, "safekeyexpire");
            return (Criteria) this;
        }

        public Criteria andSafekeyexpireBetween(Date value1, Date value2) {
            addCriterion("safeKeyExpire between", value1, value2, "safekeyexpire");
            return (Criteria) this;
        }

        public Criteria andSafekeyexpireNotBetween(Date value1, Date value2) {
            addCriterion("safeKeyExpire not between", value1, value2, "safekeyexpire");
            return (Criteria) this;
        }

        public Criteria andSafekeyvalueIsNull() {
            addCriterion("safeKeyValue is null");
            return (Criteria) this;
        }

        public Criteria andSafekeyvalueIsNotNull() {
            addCriterion("safeKeyValue is not null");
            return (Criteria) this;
        }

        public Criteria andSafekeyvalueEqualTo(String value) {
            addCriterion("safeKeyValue =", value, "safekeyvalue");
            return (Criteria) this;
        }

        public Criteria andSafekeyvalueNotEqualTo(String value) {
            addCriterion("safeKeyValue <>", value, "safekeyvalue");
            return (Criteria) this;
        }

        public Criteria andSafekeyvalueGreaterThan(String value) {
            addCriterion("safeKeyValue >", value, "safekeyvalue");
            return (Criteria) this;
        }

        public Criteria andSafekeyvalueGreaterThanOrEqualTo(String value) {
            addCriterion("safeKeyValue >=", value, "safekeyvalue");
            return (Criteria) this;
        }

        public Criteria andSafekeyvalueLessThan(String value) {
            addCriterion("safeKeyValue <", value, "safekeyvalue");
            return (Criteria) this;
        }

        public Criteria andSafekeyvalueLessThanOrEqualTo(String value) {
            addCriterion("safeKeyValue <=", value, "safekeyvalue");
            return (Criteria) this;
        }

        public Criteria andSafekeyvalueLike(String value) {
            addCriterion("safeKeyValue like", value, "safekeyvalue");
            return (Criteria) this;
        }

        public Criteria andSafekeyvalueNotLike(String value) {
            addCriterion("safeKeyValue not like", value, "safekeyvalue");
            return (Criteria) this;
        }

        public Criteria andSafekeyvalueIn(List<String> values) {
            addCriterion("safeKeyValue in", values, "safekeyvalue");
            return (Criteria) this;
        }

        public Criteria andSafekeyvalueNotIn(List<String> values) {
            addCriterion("safeKeyValue not in", values, "safekeyvalue");
            return (Criteria) this;
        }

        public Criteria andSafekeyvalueBetween(String value1, String value2) {
            addCriterion("safeKeyValue between", value1, value2, "safekeyvalue");
            return (Criteria) this;
        }

        public Criteria andSafekeyvalueNotBetween(String value1, String value2) {
            addCriterion("safeKeyValue not between", value1, value2, "safekeyvalue");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNull() {
            addCriterion("area_id is null");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNotNull() {
            addCriterion("area_id is not null");
            return (Criteria) this;
        }

        public Criteria andAreaIdEqualTo(Integer value) {
            addCriterion("area_id =", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotEqualTo(Integer value) {
            addCriterion("area_id <>", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThan(Integer value) {
            addCriterion("area_id >", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("area_id >=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThan(Integer value) {
            addCriterion("area_id <", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThanOrEqualTo(Integer value) {
            addCriterion("area_id <=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIn(List<Integer> values) {
            addCriterion("area_id in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotIn(List<Integer> values) {
            addCriterion("area_id not in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdBetween(Integer value1, Integer value2) {
            addCriterion("area_id between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotBetween(Integer value1, Integer value2) {
            addCriterion("area_id not between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andIsactivateemailIsNull() {
            addCriterion("isActivateEmail is null");
            return (Criteria) this;
        }

        public Criteria andIsactivateemailIsNotNull() {
            addCriterion("isActivateEmail is not null");
            return (Criteria) this;
        }

        public Criteria andIsactivateemailEqualTo(Boolean value) {
            addCriterion("isActivateEmail =", value, "isactivateemail");
            return (Criteria) this;
        }

        public Criteria andIsactivateemailNotEqualTo(Boolean value) {
            addCriterion("isActivateEmail <>", value, "isactivateemail");
            return (Criteria) this;
        }

        public Criteria andIsactivateemailGreaterThan(Boolean value) {
            addCriterion("isActivateEmail >", value, "isactivateemail");
            return (Criteria) this;
        }

        public Criteria andIsactivateemailGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isActivateEmail >=", value, "isactivateemail");
            return (Criteria) this;
        }

        public Criteria andIsactivateemailLessThan(Boolean value) {
            addCriterion("isActivateEmail <", value, "isactivateemail");
            return (Criteria) this;
        }

        public Criteria andIsactivateemailLessThanOrEqualTo(Boolean value) {
            addCriterion("isActivateEmail <=", value, "isactivateemail");
            return (Criteria) this;
        }

        public Criteria andIsactivateemailIn(List<Boolean> values) {
            addCriterion("isActivateEmail in", values, "isactivateemail");
            return (Criteria) this;
        }

        public Criteria andIsactivateemailNotIn(List<Boolean> values) {
            addCriterion("isActivateEmail not in", values, "isactivateemail");
            return (Criteria) this;
        }

        public Criteria andIsactivateemailBetween(Boolean value1, Boolean value2) {
            addCriterion("isActivateEmail between", value1, value2, "isactivateemail");
            return (Criteria) this;
        }

        public Criteria andIsactivateemailNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isActivateEmail not between", value1, value2, "isactivateemail");
            return (Criteria) this;
        }

        public Criteria andInvitecodeIsNull() {
            addCriterion("inviteCode is null");
            return (Criteria) this;
        }

        public Criteria andInvitecodeIsNotNull() {
            addCriterion("inviteCode is not null");
            return (Criteria) this;
        }

        public Criteria andInvitecodeEqualTo(String value) {
            addCriterion("inviteCode =", value, "invitecode");
            return (Criteria) this;
        }

        public Criteria andInvitecodeNotEqualTo(String value) {
            addCriterion("inviteCode <>", value, "invitecode");
            return (Criteria) this;
        }

        public Criteria andInvitecodeGreaterThan(String value) {
            addCriterion("inviteCode >", value, "invitecode");
            return (Criteria) this;
        }

        public Criteria andInvitecodeGreaterThanOrEqualTo(String value) {
            addCriterion("inviteCode >=", value, "invitecode");
            return (Criteria) this;
        }

        public Criteria andInvitecodeLessThan(String value) {
            addCriterion("inviteCode <", value, "invitecode");
            return (Criteria) this;
        }

        public Criteria andInvitecodeLessThanOrEqualTo(String value) {
            addCriterion("inviteCode <=", value, "invitecode");
            return (Criteria) this;
        }

        public Criteria andInvitecodeLike(String value) {
            addCriterion("inviteCode like", value, "invitecode");
            return (Criteria) this;
        }

        public Criteria andInvitecodeNotLike(String value) {
            addCriterion("inviteCode not like", value, "invitecode");
            return (Criteria) this;
        }

        public Criteria andInvitecodeIn(List<String> values) {
            addCriterion("inviteCode in", values, "invitecode");
            return (Criteria) this;
        }

        public Criteria andInvitecodeNotIn(List<String> values) {
            addCriterion("inviteCode not in", values, "invitecode");
            return (Criteria) this;
        }

        public Criteria andInvitecodeBetween(String value1, String value2) {
            addCriterion("inviteCode between", value1, value2, "invitecode");
            return (Criteria) this;
        }

        public Criteria andInvitecodeNotBetween(String value1, String value2) {
            addCriterion("inviteCode not between", value1, value2, "invitecode");
            return (Criteria) this;
        }

        public Criteria andPromoterIdIsNull() {
            addCriterion("promoter_id is null");
            return (Criteria) this;
        }

        public Criteria andPromoterIdIsNotNull() {
            addCriterion("promoter_id is not null");
            return (Criteria) this;
        }

        public Criteria andPromoterIdEqualTo(Long value) {
            addCriterion("promoter_id =", value, "promoterId");
            return (Criteria) this;
        }

        public Criteria andPromoterIdNotEqualTo(Long value) {
            addCriterion("promoter_id <>", value, "promoterId");
            return (Criteria) this;
        }

        public Criteria andPromoterIdGreaterThan(Long value) {
            addCriterion("promoter_id >", value, "promoterId");
            return (Criteria) this;
        }

        public Criteria andPromoterIdGreaterThanOrEqualTo(Long value) {
            addCriterion("promoter_id >=", value, "promoterId");
            return (Criteria) this;
        }

        public Criteria andPromoterIdLessThan(Long value) {
            addCriterion("promoter_id <", value, "promoterId");
            return (Criteria) this;
        }

        public Criteria andPromoterIdLessThanOrEqualTo(Long value) {
            addCriterion("promoter_id <=", value, "promoterId");
            return (Criteria) this;
        }

        public Criteria andPromoterIdIn(List<Long> values) {
            addCriterion("promoter_id in", values, "promoterId");
            return (Criteria) this;
        }

        public Criteria andPromoterIdNotIn(List<Long> values) {
            addCriterion("promoter_id not in", values, "promoterId");
            return (Criteria) this;
        }

        public Criteria andPromoterIdBetween(Long value1, Long value2) {
            addCriterion("promoter_id between", value1, value2, "promoterId");
            return (Criteria) this;
        }

        public Criteria andPromoterIdNotBetween(Long value1, Long value2) {
            addCriterion("promoter_id not between", value1, value2, "promoterId");
            return (Criteria) this;
        }

        public Criteria andZhifubaoaccountIsNull() {
            addCriterion("zhifubaoAccount is null");
            return (Criteria) this;
        }

        public Criteria andZhifubaoaccountIsNotNull() {
            addCriterion("zhifubaoAccount is not null");
            return (Criteria) this;
        }

        public Criteria andZhifubaoaccountEqualTo(String value) {
            addCriterion("zhifubaoAccount =", value, "zhifubaoaccount");
            return (Criteria) this;
        }

        public Criteria andZhifubaoaccountNotEqualTo(String value) {
            addCriterion("zhifubaoAccount <>", value, "zhifubaoaccount");
            return (Criteria) this;
        }

        public Criteria andZhifubaoaccountGreaterThan(String value) {
            addCriterion("zhifubaoAccount >", value, "zhifubaoaccount");
            return (Criteria) this;
        }

        public Criteria andZhifubaoaccountGreaterThanOrEqualTo(String value) {
            addCriterion("zhifubaoAccount >=", value, "zhifubaoaccount");
            return (Criteria) this;
        }

        public Criteria andZhifubaoaccountLessThan(String value) {
            addCriterion("zhifubaoAccount <", value, "zhifubaoaccount");
            return (Criteria) this;
        }

        public Criteria andZhifubaoaccountLessThanOrEqualTo(String value) {
            addCriterion("zhifubaoAccount <=", value, "zhifubaoaccount");
            return (Criteria) this;
        }

        public Criteria andZhifubaoaccountLike(String value) {
            addCriterion("zhifubaoAccount like", value, "zhifubaoaccount");
            return (Criteria) this;
        }

        public Criteria andZhifubaoaccountNotLike(String value) {
            addCriterion("zhifubaoAccount not like", value, "zhifubaoaccount");
            return (Criteria) this;
        }

        public Criteria andZhifubaoaccountIn(List<String> values) {
            addCriterion("zhifubaoAccount in", values, "zhifubaoaccount");
            return (Criteria) this;
        }

        public Criteria andZhifubaoaccountNotIn(List<String> values) {
            addCriterion("zhifubaoAccount not in", values, "zhifubaoaccount");
            return (Criteria) this;
        }

        public Criteria andZhifubaoaccountBetween(String value1, String value2) {
            addCriterion("zhifubaoAccount between", value1, value2, "zhifubaoaccount");
            return (Criteria) this;
        }

        public Criteria andZhifubaoaccountNotBetween(String value1, String value2) {
            addCriterion("zhifubaoAccount not between", value1, value2, "zhifubaoaccount");
            return (Criteria) this;
        }

        public Criteria andIsactivatemobileIsNull() {
            addCriterion("isActivateMobile is null");
            return (Criteria) this;
        }

        public Criteria andIsactivatemobileIsNotNull() {
            addCriterion("isActivateMobile is not null");
            return (Criteria) this;
        }

        public Criteria andIsactivatemobileEqualTo(String value) {
            addCriterion("isActivateMobile =", value, "isactivatemobile");
            return (Criteria) this;
        }

        public Criteria andIsactivatemobileNotEqualTo(String value) {
            addCriterion("isActivateMobile <>", value, "isactivatemobile");
            return (Criteria) this;
        }

        public Criteria andIsactivatemobileGreaterThan(String value) {
            addCriterion("isActivateMobile >", value, "isactivatemobile");
            return (Criteria) this;
        }

        public Criteria andIsactivatemobileGreaterThanOrEqualTo(String value) {
            addCriterion("isActivateMobile >=", value, "isactivatemobile");
            return (Criteria) this;
        }

        public Criteria andIsactivatemobileLessThan(String value) {
            addCriterion("isActivateMobile <", value, "isactivatemobile");
            return (Criteria) this;
        }

        public Criteria andIsactivatemobileLessThanOrEqualTo(String value) {
            addCriterion("isActivateMobile <=", value, "isactivatemobile");
            return (Criteria) this;
        }

        public Criteria andIsactivatemobileLike(String value) {
            addCriterion("isActivateMobile like", value, "isactivatemobile");
            return (Criteria) this;
        }

        public Criteria andIsactivatemobileNotLike(String value) {
            addCriterion("isActivateMobile not like", value, "isactivatemobile");
            return (Criteria) this;
        }

        public Criteria andIsactivatemobileIn(List<String> values) {
            addCriterion("isActivateMobile in", values, "isactivatemobile");
            return (Criteria) this;
        }

        public Criteria andIsactivatemobileNotIn(List<String> values) {
            addCriterion("isActivateMobile not in", values, "isactivatemobile");
            return (Criteria) this;
        }

        public Criteria andIsactivatemobileBetween(String value1, String value2) {
            addCriterion("isActivateMobile between", value1, value2, "isactivatemobile");
            return (Criteria) this;
        }

        public Criteria andIsactivatemobileNotBetween(String value1, String value2) {
            addCriterion("isActivateMobile not between", value1, value2, "isactivatemobile");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_member
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_member
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}