package com.yfyk.entity;

import java.util.Date;

public class WithDraw {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_withdraw.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_withdraw.createDate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_withdraw.modifyDate
     *
     * @mbggenerated
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_withdraw.amount
     *
     * @mbggenerated
     */
    private Float amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_withdraw.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_withdraw.bankAccount_id
     *
     * @mbggenerated
     */
    private Integer bankaccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_withdraw.member_id
     *
     * @mbggenerated
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_withdraw.checkDate
     *
     * @mbggenerated
     */
    private Date checkdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_withdraw.checkContent
     *
     * @mbggenerated
     */
    private String checkcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_withdraw.operate_id
     *
     * @mbggenerated
     */
    private Integer operateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_withdraw.id
     *
     * @return the value of t_withdraw.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_withdraw.id
     *
     * @param id the value for t_withdraw.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_withdraw.createDate
     *
     * @return the value of t_withdraw.createDate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_withdraw.createDate
     *
     * @param createdate the value for t_withdraw.createDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_withdraw.modifyDate
     *
     * @return the value of t_withdraw.modifyDate
     *
     * @mbggenerated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_withdraw.modifyDate
     *
     * @param modifydate the value for t_withdraw.modifyDate
     *
     * @mbggenerated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_withdraw.amount
     *
     * @return the value of t_withdraw.amount
     *
     * @mbggenerated
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_withdraw.amount
     *
     * @param amount the value for t_withdraw.amount
     *
     * @mbggenerated
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_withdraw.status
     *
     * @return the value of t_withdraw.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_withdraw.status
     *
     * @param status the value for t_withdraw.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_withdraw.bankAccount_id
     *
     * @return the value of t_withdraw.bankAccount_id
     *
     * @mbggenerated
     */
    public Integer getBankaccountId() {
        return bankaccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_withdraw.bankAccount_id
     *
     * @param bankaccountId the value for t_withdraw.bankAccount_id
     *
     * @mbggenerated
     */
    public void setBankaccountId(Integer bankaccountId) {
        this.bankaccountId = bankaccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_withdraw.member_id
     *
     * @return the value of t_withdraw.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_withdraw.member_id
     *
     * @param memberId the value for t_withdraw.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_withdraw.checkDate
     *
     * @return the value of t_withdraw.checkDate
     *
     * @mbggenerated
     */
    public Date getCheckdate() {
        return checkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_withdraw.checkDate
     *
     * @param checkdate the value for t_withdraw.checkDate
     *
     * @mbggenerated
     */
    public void setCheckdate(Date checkdate) {
        this.checkdate = checkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_withdraw.checkContent
     *
     * @return the value of t_withdraw.checkContent
     *
     * @mbggenerated
     */
    public String getCheckcontent() {
        return checkcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_withdraw.checkContent
     *
     * @param checkcontent the value for t_withdraw.checkContent
     *
     * @mbggenerated
     */
    public void setCheckcontent(String checkcontent) {
        this.checkcontent = checkcontent == null ? null : checkcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_withdraw.operate_id
     *
     * @return the value of t_withdraw.operate_id
     *
     * @mbggenerated
     */
    public Integer getOperateId() {
        return operateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_withdraw.operate_id
     *
     * @param operateId the value for t_withdraw.operate_id
     *
     * @mbggenerated
     */
    public void setOperateId(Integer operateId) {
        this.operateId = operateId;
    }
}