package com.yfyk.dao.mbg;

import com.yfyk.entity.Expenses;
import com.yfyk.entity.ExpensesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExpensesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expenses
     *
     * @mbggenerated
     */
    int countByExample(ExpensesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expenses
     *
     * @mbggenerated
     */
    int deleteByExample(ExpensesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expenses
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expenses
     *
     * @mbggenerated
     */
    int insert(Expenses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expenses
     *
     * @mbggenerated
     */
    int insertSelective(Expenses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expenses
     *
     * @mbggenerated
     */
    List<Expenses> selectByExample(ExpensesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expenses
     *
     * @mbggenerated
     */
    Expenses selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expenses
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Expenses record, @Param("example") ExpensesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expenses
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Expenses record, @Param("example") ExpensesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expenses
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Expenses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expenses
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Expenses record);
}