package com.yfyk.dao.mbg;

import com.yfyk.entity.HouseInfoNew;
import com.yfyk.entity.HouseInfoNewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseInfoNewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house_info_new
     *
     * @mbggenerated
     */
    int countByExample(HouseInfoNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house_info_new
     *
     * @mbggenerated
     */
    int deleteByExample(HouseInfoNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house_info_new
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house_info_new
     *
     * @mbggenerated
     */
    int insert(HouseInfoNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house_info_new
     *
     * @mbggenerated
     */
    int insertSelective(HouseInfoNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house_info_new
     *
     * @mbggenerated
     */
    List<HouseInfoNew> selectByExample(HouseInfoNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house_info_new
     *
     * @mbggenerated
     */
    HouseInfoNew selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house_info_new
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HouseInfoNew record, @Param("example") HouseInfoNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house_info_new
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HouseInfoNew record, @Param("example") HouseInfoNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house_info_new
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HouseInfoNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house_info_new
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HouseInfoNew record);
}