package com.yfyk.dao.mbg;

import com.yfyk.entity.Income;
import com.yfyk.entity.IncomeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IncomeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_income
     *
     * @mbggenerated
     */
    int countByExample(IncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_income
     *
     * @mbggenerated
     */
    int deleteByExample(IncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_income
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_income
     *
     * @mbggenerated
     */
    int insert(Income record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_income
     *
     * @mbggenerated
     */
    int insertSelective(Income record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_income
     *
     * @mbggenerated
     */
    List<Income> selectByExample(IncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_income
     *
     * @mbggenerated
     */
    Income selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_income
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Income record, @Param("example") IncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_income
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Income record, @Param("example") IncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_income
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Income record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_income
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Income record);
}