package com.yfyk.dao.mbg;

import com.yfyk.entity.WithDraw;
import com.yfyk.entity.WithDrawExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WithDrawMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    int countByExample(WithDrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    int deleteByExample(WithDrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    int insert(WithDraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    int insertSelective(WithDraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    List<WithDraw> selectByExample(WithDrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    WithDraw selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WithDraw record, @Param("example") WithDrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WithDraw record, @Param("example") WithDrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WithDraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_withdraw
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WithDraw record);
}